std = "lua51"

codes = true
color = false

ignore = {
	"212", -- unused argument
	"213", -- unused loop variable
}

max_line_length = false

files["src/**/*.lua"] = {
	read_globals = {
		"ACCEPT",
		"CANCEL",
		"C_AddOns",
		"C_EncounterJournal",
		"C_Item",
		"C_ItemSocketInfo",
		"C_MountJournal",
		"C_PetJournal",
		"C_Timer",
		"C_Transmog",
		"C_TransmogCollection",
		"C_TransmogSets",
		"CreateFrame",
		"CloseDropDownMenus",
		"CollectionsJournal",
		"CLASS_ICON_TCOORDS",
		"bit",
		"DEFAULT_CHAT_FRAME",
		"debugprofilestop",
		"debugstack",
		"EasyMenu",
		"ElvUI",
		"EJ_GetCurrentTier",
		"EJ_GetTierInfo",
		"EJ_GetDifficulty",
		"EJ_GetInstanceByIndex",
		"EJ_GetInstanceInfo",
		"EJ_GetLootInfoByIndex",
		"EJ_GetLootInfo",
		"EJ_GetNumLoot",
		"EJ_GetNumSearchResults",
		"EJ_GetNumTiers",
		"EJ_GetSearchResultInfo",
		"EJ_IsValidInstanceDifficulty",
		"EJ_SelectInstance",
		"EJ_SelectTier",
		"EJ_SetDifficulty",
		"EXPANSION_NAME0",
		"EXPANSION_NAME1",
		"EXPANSION_NAME2",
		"EXPANSION_NAME3",
		"EXPANSION_NAME4",
		"EXPANSION_NAME5",
		"EXPANSION_NAME6",
		"EXPANSION_NAME7",
		"EXPANSION_NAME8",
		"EXPANSION_NAME9",
		"EXPANSION_NAME10",
		"GameFontDisable",
		"GameFontDisableSmall",
		"GameFontHighlight",
		"GameFontHighlightSmall",
		"GameFontNormal",
		"GameFontNormalLarge",
		"GameFontNormalSmall",
		"GameTooltip",
		"GetAddOnMetadata",
		"GetAverageItemLevel",
		"GetClassColor",
		"GetClassInfo",
		"GetCursorPosition",
		"GetCurrentMapAreaID",
		"GetDifficultyInfo",
		"GetInstanceInfo",
		"GetInventoryItemLink",
		"GetItemInfo",
		"GetItemInfoInstant",
		"GetMapNameByID",
		"GetNumSavedInstances",
		"GetRealmName",
		"GetSavedInstanceEncounterInfo",
		"GetSavedInstanceInfo",
		"GetServerTime",
		"GetSpecializationInfoForClassID",
		"GetTime",
		"GetTimePreciseSec",
		"GetWeaponEnchantInfo",
		"GetBuildInfo",
		"HideUIPanel",
		"hooksecurefunc",
		"IsControlKeyDown",
		"IsShiftKeyDown",
		"HideUIPanel",
		"InterfaceOptionsFrame_OpenToCategory",
		"IsAddOnLoaded",
		"ITEM_QUALITY_COLORS",
		"LibStub",
		"LoadAddOn",
		"Minimap",
		"MogTrackerPanel",
		"MogTrackerPanelCheckbox1",
		"MogTrackerPanelCheckbox2",
		"MogTrackerPanelCheckbox3",
		"MogTrackerPanelClassScrollChild",
		"MogTrackerPanelClassScrollFrame",
		"MogTrackerPanelClassHeader",
		"MogTrackerPanelCloseButton",
		"MogTrackerPanelConfigDescription",
		"MogTrackerPanelConfigHeader",
		"MogTrackerPanelConfigLootHeader",
		"MogTrackerPanelFooter",
		"MogTrackerPanelItemHeader",
		"MogTrackerPanelItemScrollChild",
		"MogTrackerPanelItemScrollFrame",
		"MogTrackerPanelListHeader",
		"MogTrackerPanelNavClassButton",
		"MogTrackerPanelNavConfigButton",
		"MogTrackerPanelNavDebugButton",
		"MogTrackerPanelNavDebugHeader",
		"MogTrackerPanelNavFiltersHeader",
		"MogTrackerPanelNavHeader",
		"MogTrackerPanelNavLootButton",
		"MogTrackerPanelRefreshButton",
		"MogTrackerPanelResetButton",
		"MogTrackerPanelScrollChild",
		"MogTrackerPanelScrollFrame",
		"MogTrackerPanelSlider",
		"MogTrackerPanelStyleDropdownButton",
		"MogTrackerPanelStyleHeader",
		"MogTrackerPanelSubtitle",
		"MogTrackerPanelTitle",
		"MogTrackerDebugPanel",
		"MogTrackerDebugPanelCloseButton",
		"MogTrackerDebugPanelFooter",
		"MogTrackerDebugPanelListHeader",
		"MogTrackerDebugPanelRefreshButton",
		"MogTrackerDebugPanelScrollChild",
		"MogTrackerDebugPanelScrollFrame",
		"MogTrackerDebugPanelSectionsHeader",
		"MogTrackerDebugPanelSubtitle",
		"MogTrackerDebugPanelTitle",
		"NUM_CLASSES",
		"OpenTransmogCollection",
		"PanelTemplates_SetTab",
		"PlaySound",
		"RAID_CLASS_COLORS",
		"ReloadUI",
		"ResetInstances",
		"RequestRaidInfo",
		"SLASH_MOGTRACKERDEBUG1",
		"ShowUIPanel",
		"STATICPOPUP_NUMDIALOGS",
		"StaticPopup_Show",
		"SOUNDKIT",
		"UIDropDownMenu_AddButton",
		"UIDropDownMenu_CreateInfo",
		"UIDropDownMenu_Initialize",
		"ToggleCharacter",
		"ToggleDropDownMenu",
		"UIParent",
		"UIParentLoadAddOn",
		"UnitClass",
		"UnitGUID",
		"UnitLevel",
		"UnitName",
		"UISpecialFrames",
		"WardrobeCollectionFrame",
		"wipe",
		"strtrim",
		"time",
	},
	globals = {
		"CodexExampleAddonDB",
		"MogTrackerDB",
		"SLASH_MOGTRACKER1",
		"SLASH_MOGTRACKER2",
		"SLASH_MOGTRACKER3",
		"SLASH_MOGTRACKER4",
		"SlashCmdList",
		"StaticPopupDialogs",
		"TransmogTrackerDB",
		"UISpecialFrames",
	},
}

files["tests/**/*.lua"] = {
	std = "lua54",
}

files["tools/**/*.lua"] = {
	std = "lua54",
}
