local _, addon = ...

addon.CoreMetadata = {
	selectableClasses = {
		"PRIEST",
		"WARRIOR",
		"PALADIN",
		"HUNTER",
		"ROGUE",
		"DEATHKNIGHT",
		"SHAMAN",
		"MAGE",
		"WARLOCK",
		"MONK",
		"DRUID",
		"DEMONHUNTER",
		"EVOKER",
	},
	classFilterArmorGroups = {
		{
			key = "CLOTH",
			label = "布甲",
			classes = { "PRIEST", "MAGE", "WARLOCK" },
		},
		{
			key = "LEATHER",
			label = "皮甲",
			classes = { "DRUID", "ROGUE", "MONK", "DEMONHUNTER" },
		},
		{
			key = "PLATE",
			label = "板甲",
			classes = { "DEATHKNIGHT", "WARRIOR", "PALADIN" },
		},
		{
			key = "MAIL",
			label = "锁甲",
			classes = { "EVOKER", "HUNTER", "SHAMAN" },
		},
	},
	lootTypeGroups = {
		{
			key = "ARMOR",
			label = "护甲",
			types = { "CLOTH", "LEATHER", "MAIL", "PLATE", "BACK", "SHIELD", "OFF_HAND" },
		},
		{
			key = "WEAPON",
			label = "武器",
			types = {
				"ONE_HAND",
				"TWO_HAND",
				"DAGGER",
				"WAND",
				"BOW",
				"GUN",
				"CROSSBOW",
				"POLEARM",
				"STAFF",
				"FIST",
				"AXE",
				"MACE",
				"SWORD",
			},
		},
		{
			key = "COLLECTIBLES",
			label = "坐骑 / 宠物",
			types = { "MOUNT", "PET" },
		},
		{
			key = "OTHER",
			label = "其他",
			types = { "RING", "NECK", "TRINKET", "MISC" },
		},
	},
	classMaskByFile = {
		WARRIOR = 1,
		PALADIN = 2,
		HUNTER = 4,
		ROGUE = 8,
		PRIEST = 16,
		DEATHKNIGHT = 32,
		SHAMAN = 64,
		MAGE = 128,
		WARLOCK = 256,
		MONK = 512,
		DRUID = 1024,
		DEMONHUNTER = 2048,
		EVOKER = 4096,
	},
	raidTierByName = {
		["熔火之心"] = "T1",
		["Molten Core"] = "T1",
		["黑翼之巢"] = "T2",
		["Blackwing Lair"] = "T2",
		["安其拉神殿"] = "T2.5",
		["Temple of Ahn'Qiraj"] = "T2.5",
		["纳克萨玛斯"] = "T3",
		["Naxxramas"] = "T3",
		["卡拉赞"] = "T4",
		["Karazhan"] = "T4",
		["格鲁尔的巢穴"] = "T4",
		["Gruul's Lair"] = "T4",
		["玛瑟里顿的巢穴"] = "T4",
		["Magtheridon's Lair"] = "T4",
		["盘牙湖泊：毒蛇神殿"] = "T5",
		["毒蛇神殿"] = "T5",
		["Serpentshrine Cavern"] = "T5",
		["风暴要塞"] = "T5",
		["Tempest Keep"] = "T5",
		["海加尔山之战"] = "T6",
		["Battle for Mount Hyjal"] = "T6",
		["黑暗神殿"] = "T6",
		["Black Temple"] = "T6",
		["奥杜尔"] = "T8",
		["Ulduar"] = "T8",
		["十字军的试炼"] = "T9",
		["Trial of the Crusader"] = "T9",
		["冰冠堡垒"] = "T10",
		["Icecrown Citadel"] = "T10",
		["黑翼血环"] = "T11",
		["Blackwing Descent"] = "T11",
		["暮光堡垒"] = "T11",
		["The Bastion of Twilight"] = "T11",
		["风神王座"] = "T11",
		["Throne of the Four Winds"] = "T11",
		["火焰之地"] = "T12",
		["Firelands"] = "T12",
		["巨龙之魂"] = "T13",
		["Dragon Soul"] = "T13",
		["魔古山宝库"] = "T14",
		["Mogu'shan Vaults"] = "T14",
		["恐惧之心"] = "T14",
		["Heart of Fear"] = "T14",
		["永春台"] = "T14",
		["Terrace of Endless Spring"] = "T14",
		["雷电王座"] = "T15",
		["Throne of Thunder"] = "T15",
		["决战奥格瑞玛"] = "T16",
		["Siege of Orgrimmar"] = "T16",
		["悬槌堡"] = "T17",
		["Highmaul"] = "T17",
		["黑石铸造厂"] = "T17",
		["Blackrock Foundry"] = "T17",
		["地狱火堡垒"] = "T18",
		["Hellfire Citadel"] = "T18",
		["翡翠梦魇"] = "T19",
		["The Emerald Nightmare"] = "T19",
		["暗夜要塞"] = "T19",
		["The Nighthold"] = "T19",
		["萨格拉斯之墓"] = "T20",
		["Tomb of Sargeras"] = "T20",
		["安托鲁斯，燃烧王座"] = "T21",
		["Antorus, the Burning Throne"] = "T21",
		["奥迪尔"] = "T22",
		["Uldir"] = "T22",
		["达萨罗之战"] = "T23",
		["Battle of Dazar'alor"] = "T23",
		["永恒王宫"] = "T24",
		["The Eternal Palace"] = "T24",
		["尼奥罗萨，觉醒之城"] = "T25",
		["Ny'alotha, the Waking City"] = "T25",
		["纳斯利亚堡"] = "T26",
		["Castle Nathria"] = "T26",
		["统御圣所"] = "T27",
		["Sanctum of Domination"] = "T27",
		["初诞者圣墓"] = "T28",
		["Sepulcher of the First Ones"] = "T28",
		["化身巨龙牢窟"] = "T29",
		["Vault of the Incarnates"] = "T29",
		["亚贝鲁斯，焰影熔炉"] = "T30",
		["Aberrus, the Shadowed Crucible"] = "T30",
		["阿梅达希尔，梦境之愿"] = "T31",
		["Amirdrassil, the Dream's Hope"] = "T31",
	},
	lootTypeOrder = {
		"PLATE",
		"MAIL",
		"LEATHER",
		"CLOTH",
		"BACK",
		"SHIELD",
		"OFF_HAND",
		"ONE_HAND",
		"TWO_HAND",
		"DAGGER",
		"WAND",
		"BOW",
		"GUN",
		"CROSSBOW",
		"POLEARM",
		"STAFF",
		"FIST",
		"AXE",
		"MACE",
		"SWORD",
		"RING",
		"NECK",
		"TRINKET",
		"MOUNT",
		"PET",
		"MISC",
	},
}
